//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHostsUpdateGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoHostsUpdateGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BasicSettingsPanel {
            get {
                return ResourceManager.GetString("BasicSettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportErrorMessageBoxText {
            get {
                return ResourceManager.GetString("ExportErrorMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML File (*.xml)|*.xml|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportFileDialogFilter {
            get {
                return ResourceManager.GetString("ExportFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExportSuccessMessageBoxText {
            get {
                return ResourceManager.GetString("ExportSuccessMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto update for external Hosts file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalHostsPathCheckBox {
            get {
                return ResourceManager.GetString("ExternalHostsPathCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Hosts file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalHostsPathTextBlock {
            get {
                return ResourceManager.GetString("ExternalHostsPathTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportErrorMessageBoxText {
            get {
                return ResourceManager.GetString("ImportErrorMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML File (*.xml)|*.xml|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportFileDialogFilter {
            get {
                return ResourceManager.GetString("ImportFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportSuccessMessageBoxText {
            get {
                return ResourceManager.GetString("ImportSuccessMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto update for internal Hosts file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InternalHostsPathCheckBox {
            get {
                return ResourceManager.GetString("InternalHostsPathCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal Hosts file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InternalHostsPathTextBlock {
            get {
                return ResourceManager.GetString("InternalHostsPathTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export Settings(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Settings(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AutoHostsUpdateGUI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network logon if necessary to access external Hosts file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkAuthenticationCheckBox {
            get {
                return ResourceManager.GetString("NetworkAuthenticationCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkAuthenticationPanel {
            get {
                return ResourceManager.GetString("NetworkAuthenticationPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkAuthenticationPasswordTextBlock {
            get {
                return ResourceManager.GetString("NetworkAuthenticationPasswordTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkAuthenticationUsernameTextBlock {
            get {
                return ResourceManager.GetString("NetworkAuthenticationUsernameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hosts File|hosts|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServiceCancelButton {
            get {
                return ResourceManager.GetString("ServiceCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServiceStartButton {
            get {
                return ResourceManager.GetString("ServiceStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServiceStopButton {
            get {
                return ResourceManager.GetString("ServiceStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue Pending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusContinuePending {
            get {
                return ResourceManager.GetString("StatusContinuePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause Pending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusPausePending {
            get {
                return ResourceManager.GetString("StatusPausePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Pending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusStartPending {
            get {
                return ResourceManager.GetString("StatusStartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Pending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusStopPending {
            get {
                return ResourceManager.GetString("StatusStopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AutoHostsUpdateService: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusTitle {
            get {
                return ResourceManager.GetString("StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusUndefined {
            get {
                return ResourceManager.GetString("StatusUndefined", resourceCulture);
            }
        }
    }
}
